
export const countryList = [
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Belgium",
    "Austria",
    "Ireland",
    "Finland",
    "Portugal",
    "Greece",
    "India",
    "Pakistan",
    "Japan",
    "China",
    "Brazil",
    "Mexico",
    "Russia",
    "South Africa",
    "New Zealand",
    "Switzerland",
    "United Arab Emirates",
    "Saudi Arabia",
    "Singapore",
    "Hong Kong",
    "Sweden",
    "Norway",
    "Denmark",
    "Poland",
    "Turkey",
    "Thailand",
    "Malaysia",
    "Indonesia",
    "Philippines",
    "Vietnam",
    "South Korea",
    "Taiwan",
    "Israel",
    "Egypt",
    "Nigeria",
    "Bangladesh",
  ];

export const getCurrencyCode = (countryName) => {
  if (!countryName) return null;

  const countryToCurrency = {
    "United States": "usd",
    "United Kingdom": "gbp",
    "Canada": "cad",
    "Australia": "aud",
    "Germany": "eur",
    "France": "eur",
    "Italy": "eur",
    "Spain": "eur",
    "Netherlands": "eur",
    "Belgium": "eur",
    "Austria": "eur",
    "Ireland": "eur",
    "Finland": "eur",
    "Portugal": "eur",
    "Greece": "eur",
    "India": "inr",
    "Pakistan": "pkr",
    "Japan": "jpy",
    "China": "cny",
    "Brazil": "brl",
    "Mexico": "mxn",
    "Russia": "rub",
    "South Africa": "zar",
    "New Zealand": "nzd",
    "Switzerland": "chf",
    "United Arab Emirates": "aed",
    "Saudi Arabia": "sar",
    "Singapore": "sgd",
    "Hong Kong": "hkd",
    "Sweden": "sek",
    "Norway": "nok",
    "Denmark": "dkk",
    "Poland": "pln",
    "Turkey": "try",
    "Thailand": "thb",
    "Malaysia": "myr",
    "Indonesia": "idr",
    "Philippines": "php",
    "Vietnam": "vnd",
    "South Korea": "krw",
    "Taiwan": "twd",
    "Israel": "ils",
    "Egypt": "egp",
    "Nigeria": "ngn",
    "Bangladesh": "bdt",
  };

  const normalizedCountry = countryName.trim();
  const foundCountry = Object.keys(countryToCurrency).find(
    (key) => key.toLowerCase() === normalizedCountry.toLowerCase()
  );

  return foundCountry ? countryToCurrency[foundCountry] : null; 
};
